### ISSUE TITLE
api/review調査

### ISSUE THREAD

**Issue by moguaiyuki** [moguaiyuki/ponkotsu_store#11]
直接JSは埋め込めないけどボタンみたいなのは設置できるから，そこからcookieの情報（セッションの情報）を送ることはできる

```
<form action="hogehoge" method="post"><p>hoge<input type="text" name="name" size="40"><input type="button" value="Check" onclick="console.log(document.cookie)">
</p><input type="hidden" value="document.cookie"><input type="submit" value="ぽちっ"></form>
```

**Comment by moguaiyuki** [comment]
が，これが本当に脆弱性なのかというとなぞ

**Comment by moguaiyuki** [comment]
> session.cookie_httponlyの設定（HTTPのみクッキーを送信＝Javascriptにアクセスさせない）
デフォルト無効。有効にする。JavascriptからのセッションIDアクセスはリスク増加でしかない。
稀にCSRF対策によっては無効にできない場合もある。その場合、できるだけCSRF対策を変える。

これを設定して，JSからセッションIDアクセスをできないようにする？

**Comment by moguaiyuki** [comment]
https://blog.ohgaki.net/proper-session-id-management-php

**Comment by anddev68** [comment]
@satomari-sanから画像を埋め込めるってヒントをいただいたので

```
<iframe width="200" height="200" src="https://anddev68.github.io/simpleweb/"></iframe>
```

iframeでjsが動くようなコードを置いておき、読み込んでやると
jsが動作してしまう

**Comment by anddev68** [comment]
GitHub.io の中身はこれです

```
<!doctype html>
<html>
  <body onLoad="alert('hello');">
  </body>
</html>
```
